# Generated by Django 4.0.4 on 2022-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rate',
            field=models.FloatField(default=0),
        ),
    ]
