# Generated by Django 4.0.4 on 2022-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mid_rate',
            field=models.FloatField(default=0),
        ),
    ]
